---
- name: install nginx
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - python-httplib2

- name: configure nginx sites
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ item.key }}
    mode: "0644"
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active
  changed_when: "active.stdout_lines != sites.keys()"

# - debug: var=active.stdout_lines
# - debug: var=db_name
- debug: var=vars

- name: de-activate sites
  file:
    path: /etc/nginx/sites-enabled/{{ item }}
    state: absent
  with_items: "{{ active.stdout_lines }}"
  when: "item not in sites"
  notify: restart nginx

- name: activate nginx sites
  file:
    src: /etc/nginx/sites-available/{{ item.key }}
    dest: /etc/nginx/sites-enabled/{{ item.key }}
    state: link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes
